# -*- coding: utf-8 -*-
# Resource file generated by pyrcc5

# run "pyrcc5 -o resources_rc.py resources.qrc" to compile

from qgis.PyQt import QtCore

# import the qrc resources here if you compile them
